In [1]:
import sklearn
sklearn.__version__

'1.4.2'

In [1]:
!pip show scikit-learn # check ซ้ำด้วย

Name: scikit-learn
Version: 1.4.2
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: D:\66825\miniconda\envs\pim\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: daal4py, scikit-learn-intelex


## pip U , install 

In [ ]:
# !conda update scikit-learn  # compatible จะดีกว่า คือจะอ้างอิง library เยอะ 

In [ ]:
!pip uninstall scikit-learn

In [ ]:
!pip install scikit-learn==1.4.2 

## ถ้ามีตัว intel ละจะใช้ CPU มันจะ Accelerated ให้

In [5]:
# !conda install scikit-learn-intelex -c conda-forge # รันใน anaconda prompt 

^C


## Ordinal Encoding

In [30]:
from sklearn.preprocessing import OrdinalEncoder 

In [31]:
encoder = OrdinalEncoder() # จะ encoder ตาม row
# ถ้าเราสนใจ ลำดับ (ไม่สนใจระยะห่าง) ถึงจะใช้ # X = ['A', 'B', 'C', 'D'] งคือยกตัวอย่าง
# transfrom ไปแล้ว เราก็แปลงกลับได้ ด้วย inverse_transform

In [30]:
# X = ['A', 'B', 'C', 'D'] # ปกติเราไม่เขียนค่า X อย่างนี้ เพราะเราต้องการ attr เป็น grade แต่ ข้อมูลนี้หมายถึง 4 มิติ 
# ที่เราต้องการจริงๆ คือ 4[หมายถึง value แต่ละ grade]x1[attrbute grade]

In [76]:
X = [['A'], ['C'], ['B'], ['D']]

In [67]:
len(X)

4

In [37]:
encoder.fit(X)

OrdinalEncoder()

In [32]:
X_ = encoder.transform(X)

NotFittedError: This OrdinalEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [39]:
X_ # sparse matrix แล้วนะ # มัน sort ให้ก่อนด้วย

array([[0.],
       [2.],
       [1.],
       [3.]])

In [40]:
encoder.categories_ # ตัวแปร ภายใน ของ sk-learn คือ ลงท้ายด้วย_
# ค่าเหมือนเดิม ตัวที่0คือA ไปเรื่อยๆ ถ้าจะแปลงกลับก็ inverse

[array(['A', 'B', 'C', 'D'], dtype=object)]

In [41]:
encoder.inverse_transform(X_)

array([['A'],
       ['C'],
       ['B'],
       ['D']], dtype=object)

In [70]:
# เปรียบกับค่าตัวใหม่ ที่เป็น 1 attribute -> 2 column 4 row
X = [['A', 10], ['B', 9.5], ['C', 8], ['D', 16]]

### test

In [72]:
import pandas as pd
df = pd.DataFrame(X, columns=['name', 'score'])
df # แบบนี้เป็น 2 column

name  score
0    A   10.0
1    B    9.5
2    C    8.0
3    D   16.0

In [73]:
X[3][0]

'D'

In [39]:
for i in range(len(X)):
    # print(X[i][0])
    print(X[i][1])

10
9.5
8
16


In [40]:
# แต่มีหลายค่า
X[0]

['A', 10]

### fix to compare

In [41]:
encoder.fit(X)

OrdinalEncoder()

In [42]:
X_ = encoder.transform(X)

In [43]:
X_ 
# ที่ column 0 มองเหมือนเดิม
# column 1  ตอนแปลงกลับมา มันดูแค่ลำดับ

array([[0., 2.],
       [1., 1.],
       [2., 0.],
       [3., 3.]])

In [44]:
encoder.categories_
# X = [['A', 10], ['B', 9.5], ['C', 8], ['D', 16]]

[array(['A', 'B', 'C', 'D'], dtype=object),
 array([8, 9.5, 10, 16], dtype=object)]

In [45]:
encoder.inverse_transform(X_)

array([['A', 10],
       ['B', 9.5],
       ['C', 8],
       ['D', 16]], dtype=object)

## Label Encoder

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
encoder = LabelEncoder()

In [55]:
Y = ['bat', 'ant', 'cat', 'dog', 'ant'] # หา unique ละก็ sorting 

In [56]:
encoder.fit(Y)

LabelEncoder()

In [57]:
Y_ = encoder.transform(Y)

In [58]:
Y_

array([1, 0, 2, 3, 0])

In [59]:
# เนื่องจากเป็นค่า Y, target จึงเรียกว่า classes_
encoder.classes_

array(['ant', 'bat', 'cat', 'dog'], dtype='<U3')

In [60]:
# แปลงกลับ
encoder.inverse_transform(Y_)

array(['bat', 'ant', 'cat', 'dog', 'ant'], dtype='<U3')

## One-hot Encoding

In [61]:
from sklearn.preprocessing import OneHotEncoder

In [62]:
encoder = OneHotEncoder() # ถ้า 0 เยอะ คือมันกลวง และมันเปลือง หรือ sprase matrix โดยมันเก็บเป็นคู่ลำดับ ว่าตรงไหนมันมีเลขที่ไม่ใช่ 0 แค่นั้นเลย มี sparse ก็ต้องมี Dense สามารถใช้ .todense() ดูค่าได้ 

In [63]:
X = [['ant'], ['bat'], ['cat'], ['bat'], ['ant'], ['cat']] # attribute = 1 คือ animal

In [65]:
len(X)

6

In [66]:
encoder.fit(X)

OneHotEncoder()

In [68]:
X_ = encoder.transform(X)
X_

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [69]:
X_.todense()

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])

## MultiLabel Binarizer

In [23]:
from sklearn.preprocessing import MultiLabelBinarizer

In [ ]:
# attribute = 1 คือ ประเภทหนัง ที่เป็น multiple value ที่มี 5 
X = [['sci-fi', 'comedy']] # ตรงนี้คือมี column เดียว แบบนี้ sklearn ทำไม่ได้


## K Bins Discretizer
ของที่เหมาะกับตัวนี้ คือ พวกของที่มีค่ามากเกินไป และเราไม่สนใจค่ามัน

พวกที่เป็น นน เงินเดือน จะเป็นค่าต่อเนื่อง
พวกที่เป็น ชื่อคน เป็น dis-crete

In [24]:
from sklearn.preprocessing import KBinsDiscretizer

In [25]:
X = [[10], [11], [12], [16], [21], [22], [35]] # 7 ช่วง

In [26]:
encoder = KBinsDiscretizer(n_bins=3)#, encode='onehot', strategy='quantile') # defalt
# n_bins = จะ group มันให้เหลือกี่ group
# encode='onehot'
# strategy='quantile' # สนใจแค่ลำดับ แล้วค่อยแบ่งไป 4 เส้น

In [ ]:
X

In [ ]:
# ordinal = ordinal ค่าเรียง เริ่มที่ 0
# startegy = กระจายตัวอย่างไร แบบ uniform = สนใจระยะห่าง แล้วค่อยแบ่งไป 4 เส้น
# มองภาพว่า ค่าที่เราสนใจลำดับ เราก้ให้มันอยู่ใกล้กันได้ แค่ไม่สนระยะห่าง
# แต่ถ้า สนใจระยะห่าง ก้วาง data ตามระยะห่าง แล้วค่อยแบ่งเส้น

## MinMax Scaler

In [74]:
from sklearn.preprocessing import MinMaxScaler
# เหมาะกับ data ที่สเกล ข้อมูลที่เป็น อัตราส่วนเดิม ไม่ได้เปลี่ยน distibute ของ data

In [75]:
X = [[1], [2], [4], [5], [3]]

In [ ]:
scaler = MinMaxScaler()

## Imputation

## Feature Selection

In [74]:
from sklearn.feature_selection import VarianceThreshold

In [78]:
X = [[1, 2, 3], [5, 2, 4], [10, 2.2, 5], [12, 2.5, 6]]
X = pd.DataFrame(X, columns=['A', 'B', 'C'])
X

A    B  C
0   1  2.0  3
1   5  2.0  4
2  10  2.2  5
3  12  2.5  6

In [79]:
p = 0.8
th = p * (1 - p)
selector = VarianceThreshold(threshold=th)

In [80]:
selector.fit(X)

VarianceThreshold(threshold=0.15999999999999998)

In [ ]:
selector._

In [82]:
X_ = selector.transform(X)
X_

array([[ 1.,  3.],
       [ 5.,  4.],
       [10.,  5.],
       [12.,  6.]])

In [83]:
selector.get_feature_names_out()

array(['A', 'C'], dtype=object)

# Classification

In [ ]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, SelectPercentile, GenericUnivariateSelect, \
                                      chi2, f_classif, mutual_info_classif

## Regression

In [88]:
from sklearn.feature_selection import GenericUnivariateSelect, r_regression, f_regression, mutual_info_regression
from sklearn.datasets import load_diabetes

In [89]:
X = load_diabetes(as_frame=True)

In [90]:
X.target

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [91]:
X.data

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [ ]:
# score_func = r_regression
# score_func = f_regression
score_func = mutual_info_regression

selector = GenericUnivariateSelect(score_func=score_func, mode='k_best', param=5)
selector.fit(X.data, X.target)
print(selector.scores_)
print(selector.get_feature_names_out())

In [ ]:
# bar chart เรียงตามความสำคัญของ feature sort ด้วย ให้ user เลือก mode และ เลือกว่าจะตัดด้วยค่าเท่าไหร่

In [92]:
"r_regression"

'r_regression'

In [94]:
eval("r_regression") # # eval ทำหน้าที่ เปลี่ยน string ให้เป็น statement code ทำให้ exceute string ได้เลย

<function sklearn.feature_selection._univariate_selection.r_regression(X, y, *, center=True, force_finite=True)>

In [95]:
selector.get_support()

array([ True, False,  True])

In [96]:
selector.get_feature_names_out()

array(['A', 'C'], dtype=object)