In [1]:
import numpy as np
import sklearn
sklearn.__version__

'1.4.2'

In [1]:
# !pip show scikit-learn # check ซ้ำด้วย

Name: scikit-learn
Version: 1.4.2
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: D:\66825\miniconda\envs\pim\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: daal4py, scikit-learn-intelex


## pip U , install 

In [ ]:
# !conda update scikit-learn  # compatible จะดีกว่า คือจะอ้างอิง library เยอะ 

In [ ]:
!pip uninstall scikit-learn

In [ ]:
!pip install scikit-learn==1.4.2 

## ถ้ามีตัว intel ละจะใช้ CPU มันจะ Accelerated ให้

In [5]:
# !conda install scikit-learn-intelex -c conda-forge # รันใน anaconda prompt 

^C


## Ordinal Encoding

In [2]:
from sklearn.preprocessing import OrdinalEncoder 

In [3]:
encoder = OrdinalEncoder() # จะ encoder ตาม rown# ถ้าเราสนใจ ลำดับ (ไม่สนใจระยะห่าง) ถึงจะใช้ 
# transfrom ไปแล้ว เราก็แปลงกลับได้ ด้วย inverse_transform ได้

In [30]:
# X = ['A', 'B', 'C', 'D'] # ปกติเราไม่เขียนค่า X อย่างนี้ เพราะเราต้องการ attr เป็น grade แต่ ข้อมูลนี้หมายถึง 4 มิติ 
# ที่เราต้องการจริงๆ คือ 4[หมายถึง value แต่ละ grade]x1[attribute grade = column] 

In [4]:
X = [['A'], ['C'], ['B'], ['D']]

In [5]:
X[0] # ซึ่งยีงเป็น vector อยู่

['A']

In [6]:
len(X)

4

In [7]:
encoder.fit(X)

OrdinalEncoder()

In [8]:
X_ = encoder.transform(X)

In [9]:
X_ # sparse matrix แล้วนะ # มัน sort ให้ก่อนด้วย

array([[0.],
       [2.],
       [1.],
       [3.]])

In [10]:
encoder.categories_ # ตัวแปร ภายใน ของ sk-learn คือ ลงท้ายด้วย_
# ค่าเหมือนเดิม ตัวที ่0 คือ index 0=A ตัวที่ 1 คือ index 2=C ไปเรื่อยๆ ถ้าจะแปลงกลับก็ inverse

[array(['A', 'B', 'C', 'D'], dtype=object)]

In [11]:
encoder.inverse_transform(X_)

array([['A'],
       ['C'],
       ['B'],
       ['D']], dtype=object)

In [12]:
# เปรียบกับค่าตัวใหม่ ที่เป็น 1 attribute เช่นเดิม แต่มีค่า 2 column 4 row
X = [['A', 10], ['B', 9.5], ['C', 8], ['D', 16]]

### test

In [13]:
import pandas as pd
df = pd.DataFrame(X, columns=['name', 'score'])
df # แบบนี้เป็น 2 column

name  score
0    A   10.0
1    B    9.5
2    C    8.0
3    D   16.0

In [14]:
X[3][0]

'D'

In [16]:
for i in range(len(X)):
    print(X[i][0])
    # print(X[i][1])

A
B
C
D


In [17]:
# แต่มีหลายค่า
X[0]

['A', 10]

### fix to compare

In [18]:
encoder.fit(X)

OrdinalEncoder()

In [19]:
X_ = encoder.transform(X)

In [20]:
X_ 
# ที่ column 0 มองเหมือนเดิม
# column 1  ตอนแปลงกลับมา มันดูแค่ลำดับของค่า น้อยสุด = index 0 -> มากสุด = index 3

array([[0., 2.],
       [1., 1.],
       [2., 0.],
       [3., 3.]])

In [21]:
encoder.categories_
# X = [['A', 10], ['B', 9.5], ['C', 8], ['D', 16]]

[array(['A', 'B', 'C', 'D'], dtype=object),
 array([8, 9.5, 10, 16], dtype=object)]

In [22]:
encoder.inverse_transform(X_)

array([['A', 10],
       ['B', 9.5],
       ['C', 8],
       ['D', 16]], dtype=object)

## Label Encoder

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
encoder = LabelEncoder()

In [25]:
Y = ['bat', 'ant', 'cat', 'dog', 'ant'] # หา unique ละก็ sorting 

In [26]:
encoder.fit(Y)

LabelEncoder()

In [27]:
Y_ = encoder.transform(Y)

In [28]:
Y_

array([1, 0, 2, 3, 0])

In [29]:
# เนื่องจากเป็นค่า Y, target จึงเรียกว่า classes_
encoder.classes_

array(['ant', 'bat', 'cat', 'dog'], dtype='<U3')

In [60]:
# แปลงกลับ
encoder.inverse_transform(Y_)

array(['bat', 'ant', 'cat', 'dog', 'ant'], dtype='<U3')

## One-hot Encoding

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
encoder = OneHotEncoder() # ถ้า 0 เยอะ คือมันกลวง และมันเปลือง หรือ sprase matrix โดยมันเก็บเป็นคู่ลำดับ ว่าตรงไหนมันมีเลขที่ไม่ใช่ 0 แค่นั้นเลย มี sparse ก็ต้องมี Dense สามารถใช้ .todense() ดูค่าได้ 

In [33]:
X = [['ant'], ['bat'], ['cat'], ['bat'], ['ant'], ['cat']] # attribute = 1 คือ animal

In [34]:
len(X)

6

In [35]:
encoder.fit(X)

OneHotEncoder()

In [36]:
X_ = encoder.transform(X)
X_

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [39]:
encoder.categories_

[array(['ant', 'bat', 'cat'], dtype=object)]

In [37]:
X_.todense()

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]])

In [40]:
encoder.inverse_transform(X_)

array([['ant'],
       ['bat'],
       ['cat'],
       ['bat'],
       ['ant'],
       ['cat']], dtype=object)

In [41]:
import pandas as pd
df = pd.DataFrame(X, columns=['animal'])
df

animal
0    ant
1    bat
2    cat
3    bat
4    ant
5    cat

In [42]:
pd.get_dummies(df)

animal_ant  animal_bat  animal_cat
0        True       False       False
1       False        True       False
2       False       False        True
3       False        True       False
4        True       False       False
5       False       False        True

In [43]:
pd.get_dummies(df, dtype=int)

animal_ant  animal_bat  animal_cat
0           1           0           0
1           0           1           0
2           0           0           1
3           0           1           0
4           1           0           0
5           0           0           1

## MultiLabel Binarizer

In [47]:
from sklearn.preprocessing import MultiLabelBinarizer

In [48]:
encoder = MultiLabelBinarizer()

In [49]:
# attribute = 1 คือ ประเภทหนัง ที่เป็น multiple value ที่มี 4 เรื่อง =row แต่ละเรื่องคือ ประเภทหนังในแต่ละเรื่อง
X = [['sci-fi', 'comedy'], 
     ['comedy'], 
     ['drama', 'romance'],  
     ['sci-fi', 'drama', 'action']]  # ตรงนี้คือมี column เดียว แบบนี้ sklearn บอกออกมาเป็นช่วงไม่ได้ บอกได้แค่ว่ามีประเภทหนังนั้น ในเรื่องนั้นไหม เท่านั้น
encoder.fit(X)

MultiLabelBinarizer()

In [50]:
X_ = encoder.transform(X) # จะบอกได้แค่ว่า มีประเภทหนังอะไรในเรื่องนั้นบ้าง
X_

array([[0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 0, 1]])

In [51]:
encoder.inverse_transform(X_)

[('comedy', 'sci-fi'),
 ('comedy',),
 ('drama', 'romance'),
 ('action', 'drama', 'sci-fi')]

In [52]:
encoder.classes_

array(['action', 'comedy', 'drama', 'romance', 'sci-fi'], dtype=object)

## K Bins Discretizer
ของที่เหมาะกับตัวนี้ คือ พวกของที่มีค่ามากเกินไป และเราไม่สนใจค่ามัน เช่น เงินเดือน

พวกที่เป็น นน เงินเดือน จะเป็นค่าต่อเนื่อง
พวกที่เป็น ชื่อคน เป็น dis-crete

In [53]:
from sklearn.preprocessing import KBinsDiscretizer

In [54]:
X = [[10], [11], [12], [16], [21], [22], [35]] # 7 ช่วง

In [55]:
encoder = KBinsDiscretizer(n_bins=3)#, encode='onehot', strategy='quantile') # defalt
# n_bins = จะ group มันให้เหลือกี่ group
# encode='onehot'
# strategy='quantile' # สนใจแค่ลำดับ แล้วค่อยแบ่งไป 4 เส้น
encoder.fit(X)

KBinsDiscretizer(n_bins=3)

In [56]:
X_ = encoder.transform(X)
X_

<7x3 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [57]:
X_.todense()

matrix([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [58]:
encoder.bin_edges_

array([array([10., 12., 21., 35.])], dtype=object)

In [59]:
encoder.inverse_transform(X_)

array([[11. ],
       [11. ],
       [16.5],
       [16.5],
       [28. ],
       [28. ],
       [28. ]])

In [60]:
encoder = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile')
# ordinal = ordinal ค่าเรียง เริ่มที่ 0
# startegy = กระจายตัวอย่างไร แบบ uniform = สนใจระยะห่าง แล้วค่อยแบ่งไป 4 เส้น
# มองภาพว่า ค่าที่เราสนใจลำดับ เราก้ให้มันอยู่ใกล้กันได้ แค่ไม่สนระยะห่าง
# แต่ถ้า สนใจระยะห่าง ก้วาง data ตามระยะห่าง แล้วค่อยแบ่งเส้น

In [61]:
encoder.fit_transform(X)

array([[0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.]])

In [62]:
encoder = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
encoder.fit_transform(X) # มันจะแบ่งค่่วงต่างกัน

D:\66825\miniconda\envs\pim\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.]])

## MinMax Scaler

In [63]:
from sklearn.preprocessing import MinMaxScaler
# เหมาะกับ data ที่สเกล ข้อมูลที่เป็น อัตราส่วนเดิม ไม่ได้เปลี่ยน distibute ของ data

In [71]:
X = [[1], [2], [4], [5], [3]]

In [72]:
scaler = MinMaxScaler()

In [73]:
scaler.fit(X)
X_ = scaler.transform(X)
X_

array([[0.  ],
       [0.25],
       [0.75],
       [1.  ],
       [0.5 ]])

In [74]:
scaler.inverse_transform(X_)

array([[1.],
       [2.],
       [4.],
       [5.],
       [3.]])

## Normalization

In [85]:
from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
X = [[4, 1, 2, 2],
     [1, 3, 9, 3],
     [5, 7, 5, 1]]
normalizer.fit(X)

Normalizer()

In [86]:
X_ = normalizer.transform(X)
X_

array([[0.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])

In [79]:
len(X[0])

4

In [80]:
normalizer.inverse_transform(X_) # บางตัวก็ไม่มี

AttributeError: 'Normalizer' object has no attribute 'inverse_transform'

In [81]:
normalizer = Normalizer(norm='l1')
normalizer.fit(X)

Normalizer(norm='l1')

In [82]:
X_ = normalizer.transform(X)
X_

array([[0.44444444, 0.11111111, 0.22222222, 0.22222222],
       [0.0625    , 0.1875    , 0.5625    , 0.1875    ],
       [0.27777778, 0.38888889, 0.27777778, 0.05555556]])

## Standardization

In [88]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = [[1, 2], [2, 3], [3, 4], [4, 5]]
scaler.fit(X)

StandardScaler()

In [89]:
X_ = scaler.transform(X)
X_

array([[-1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079]])

In [90]:
scaler.mean_, scaler.var_

(array([2.5, 3.5]), array([1.25, 1.25]))

In [ ]:
scaler.inverse_transform(X_)

## Imputation

In [4]:
import numpy as np
X = [[np.nan, np.nan, 10], [4, 1, 6], [10,2,9],[10,2,9]]

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputer.fit(X)

SimpleImputer()

In [9]:
(4+10+10)/3

8.0

In [10]:
(1+2+2)/3

1.6666666666666667

In [6]:
X_ = imputer.transform(X)
X_ 

array([[ 8.        ,  1.66666667, 10.        ],
       [ 4.        ,  1.        ,  6.        ],
       [10.        ,  2.        ,  9.        ],
       [10.        ,  2.        ,  9.        ]])

In [11]:
imputer.inverse_transform(X_)

ValueError: 'inverse_transform' works only when 'SimpleImputer' is instantiated with 'add_indicator=True'. Got 'add_indicator=False' instead.

In [12]:
imputer = SimpleImputer(strategy='mean', add_indicator=True) # ต้องใส่ ตัวชี้ด้วย ถึงจะรู้ว่า nan ที่ไหน ซึ่งทำให้เปลือง memory มากขึ้น
imputer.fit(X)

SimpleImputer(add_indicator=True)

In [13]:
X_ = imputer.transform(X)
imputer.inverse_transform(X_)

array([[nan, nan, 10.],
       [ 4.,  1.,  6.],
       [10.,  2.,  9.],
       [10.,  2.,  9.]])

In [14]:
imputer = SimpleImputer(strategy='most_frequent') #== mode
imputer.fit_transform(X)

array([[10.,  2., 10.],
       [ 4.,  1.,  6.],
       [10.,  2.,  9.],
       [10.,  2.,  9.]])

In [15]:
imputer = SimpleImputer(strategy='median') # ==median 
imputer.fit_transform(X)

array([[10.,  2., 10.],
       [ 4.,  1.,  6.],
       [10.,  2.,  9.],
       [10.,  2.,  9.]])

In [16]:
imputer = SimpleImputer(strategy='constant', fill_value=-1) # ใส่ค่าคงที่
imputer.fit_transform(X)

array([[-1., -1., 10.],
       [ 4.,  1.,  6.],
       [10.,  2.,  9.],
       [10.,  2.,  9.]])

In [18]:
X = [['dog'], ['dog'], ['cat'], [np.nan]] # ถ้า data ไม่ใช่เลข

In [20]:
imputer = SimpleImputer(strategy='constant')
imputer.fit_transform(X) # missing_value คือต้องบอกค่าที่มันต้องใส่ด้วย para -> fill_value=

array([['dog'],
       ['dog'],
       ['cat'],
       ['missing_value']], dtype=object)

In [21]:
imputer = SimpleImputer(strategy='constant', fill_value='cat')
imputer.fit_transform(X)

array([['dog'],
       ['dog'],
       ['cat'],
       ['cat']], dtype=object)

In [19]:
imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X)

array([['dog'],
       ['dog'],
       ['cat'],
       ['dog']], dtype=object)

## KNN Imputer
หา distance ว่าใกล้อันไหน จะไปหยิบค่านั้นมาใส่ แต่ถ้าค่านั้นเป็น nan หละ เพราะ nan - nan ไม่ได้ จะเป็นการ return ค่า nan กลับไป

In [23]:
from sklearn.impute import KNNImputer

X = [[np.nan, np.nan, 3], [4, 1, 6], [10,2,9],[10,2,9]]
imputer = KNNImputer(n_neighbors=1)
imputer.fit(X)


KNNImputer(n_neighbors=1)

In [24]:
X_ = imputer.transform(X)
X_

array([[ 4.,  1.,  3.],
       [ 4.,  1.,  6.],
       [10.,  2.,  9.],
       [10.,  2.,  9.]])

# Feature Selection

## Variance Threshold


In [40]:
from sklearn.feature_selection import VarianceThreshold

In [42]:
import pandas as pd
X = [[1, 2, 3], [5, 2, 4], [10, 2.2, 5], [12, 2.5, 6]]
X = pd.DataFrame(X, columns=['A', 'B', 'C'])
X

A    B  C
0   1  2.0  3
1   5  2.0  4
2  10  2.2  5
3  12  2.5  6

In [43]:
p = 0.2 # จะกำหนด 0.2 or 0.8 จะได้ค่าใกล้ๆกัน
th = p * (1 - p)
th

0.16000000000000003

In [44]:
selector = VarianceThreshold(threshold=th)
selector.fit(X)

VarianceThreshold(threshold=0.16000000000000003)

In [45]:
selector.variances_

array([18.5     ,  0.041875,  1.25    ])

In [46]:
X_ = selector.transform(X)
X_

array([[ 1.,  3.],
       [ 5.,  4.],
       [10.,  5.],
       [12.,  6.]])

In [47]:
selector.get_feature_names_out()

array(['A', 'C'], dtype=object)

# Classification

In [48]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, SelectPercentile, GenericUnivariateSelect, \
                                      chi2, f_classif, mutual_info_classif

In [49]:
X = load_iris(as_frame=True)
X.data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [50]:
X.target

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [53]:
###
# ฟังก์ชันเหล่านี้ช่วยให้เลือกฟีเจอร์ที่มีประโยชน์ที่สุด
# สำหรับการสร้างโมเดลจำแนกประเภทที่มีประสิทธิภาพ
# ---
score_func = chi2 # วัดความสัมพันธ์ระหว่างฟีเจอร์แบบกลุ่ม (categorical) กับตัวแปรเป้าหมาย (target)
# โดยใช้สถิติไคสแควร์ (chi-square) ฟีเจอร์ที่มีค่า chi2 สูงบ่งบอกถึงความสัมพันธ์ที่
# แข็งแกร่งกับตัวแปรเป้าหมาย


# score_func = f_classif # วัดความสัมพันธ์ระหว่างฟีเจอร์แบบต่อเนื่อง (numerical) กับตัวแปรเป้าหมาย
# โดยใช้ ANOVA (Analysis of Variance) ฟีเจอร์ที่มีค่า f_classif สูงบ่งบอกถึงความสัมพันธ์ที่
# แข็งแกร่งกับตัวแปรเป้าหมาย
# score_func = mutual_info_classif # วัดการพึ่งพาอาศัยกันระหว่างฟีเจอร์แบบใดๆ กับตัวแปรเป้าหมาย
# โดยใช้วัดข้อมูลร่วม (mutual information) ฟีเจอร์ที่มีค่า mutual_info_classif สูงบ่งบอกถึง
# ความสัมพันธ์ที่แข็งแกร่งกับตัวแปรเป้าหมาย
# ---
###

In [54]:
# selector = SelectKBest(score_func=score_func, k=2) ## เทียบเท่าตัวล่าง 
selector = GenericUnivariateSelect(score_func=score_func, mode='k_best', param=2)
selector.fit(X.data, X.target)
print(selector.scores_)
print(selector.get_feature_names_out())

[ 10.81782088   3.7107283  116.31261309  67.0483602 ]
['petal length (cm)' 'petal width (cm)']


In [55]:
# selector = SelectPercentile(score_func=score_func, percentile=30)
selector = GenericUnivariateSelect(score_func=score_func, mode='percentile', param=30)
selector.fit(X.data, X.target)
print(selector.scores_)

[ 10.81782088   3.7107283  116.31261309  67.0483602 ]


In [56]:
selector = GenericUnivariateSelect(score_func=score_func, mode='fwe', param=0.05)
selector.fit(X.data, X.target)
print(selector.scores_)
print(selector.pvalues_)
print(selector.get_feature_names_out())

[ 10.81782088   3.7107283  116.31261309  67.0483602 ]
[4.47651499e-03 1.56395980e-01 5.53397228e-26 2.75824965e-15]
['sepal length (cm)' 'petal length (cm)' 'petal width (cm)']


## Regression

In [88]:
from sklearn.feature_selection import GenericUnivariateSelect, r_regression, f_regression, mutual_info_regression
from sklearn.datasets import load_diabetes

In [89]:
X = load_diabetes(as_frame=True)

In [90]:
X.target

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [91]:
X.data

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [ ]:
# score_func = r_regression
# score_func = f_regression
score_func = mutual_info_regression

selector = GenericUnivariateSelect(score_func=score_func, mode='k_best', param=5)
selector.fit(X.data, X.target)
print(selector.scores_)
print(selector.get_feature_names_out())

In [ ]:
# bar chart เรียงตามความสำคัญของ feature sort ด้วย ให้ user เลือก mode และ เลือกว่าจะตัดด้วยค่าเท่าไหร่

In [92]:
"r_regression"

'r_regression'

In [94]:
eval("r_regression") # # eval ทำหน้าที่ เปลี่ยน string ให้เป็น statement code ทำให้ exceute string ได้เลย

<function sklearn.feature_selection._univariate_selection.r_regression(X, y, *, center=True, force_finite=True)>

In [95]:
selector.get_support()

array([ True, False,  True])

In [96]:
selector.get_feature_names_out()

array(['A', 'C'], dtype=object)

## Feature Importance from ML 
ใช้ randomforestclass ก่อน

In [58]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier # ไม่มี feature importances
from sklearn.feature_selection import SelectFromModel # เลือกโมเดลมาเลย


In [59]:
from sklearn.datasets import load_iris
X = load_iris(as_frame=True)

In [60]:
clf = RandomForestClassifier()

In [61]:
clf.fit(X.data, X.target)

RandomForestClassifier()

In [62]:
clf.feature_importances_

array([0.09308114, 0.02093472, 0.43611752, 0.44986661])

In [63]:
selector = SelectFromModel(clf, prefit=True)

In [64]:
X.data.columns[selector.get_support()] # ใช้ selector.get_support() เป็นตัว query จาก column ที่มี

Index(['petal length (cm)', 'petal width (cm)'], dtype='object')

### Forward

In [66]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.neighbors import KNeighborsClassifier

In [67]:
clf = KNeighborsClassifier(n_neighbors=3)

In [68]:
selector = SequentialFeatureSelector(clf, n_features_to_select='auto', direction='forward')
selector.fit(X.data, X.target)
print(selector.get_feature_names_out())

['sepal length (cm)' 'petal width (cm)']


### Backward

In [69]:
selector = SequentialFeatureSelector(clf, n_features_to_select='auto', direction='backward')
selector.fit(X.data, X.target)
print(selector.get_feature_names_out())

['petal length (cm)' 'petal width (cm)']


### Recursive

In [70]:
from sklearn.feature_selection import RFE
clf = RandomForestClassifier()

In [71]:
selector = RFE(clf)
selector.fit(X.data, X.target)

RFE(estimator=RandomForestClassifier())

In [73]:
selector.get_feature_names_out()

array(['petal length (cm)', 'petal width (cm)'], dtype=object)

In [74]:
selector.get_support()

array([False, False,  True,  True])

## Cross-validation (CV)


In [75]:
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold

In [76]:
clf = RandomForestClassifier()

selector = RFECV(clf, cv=StratifiedKFold(5), scoring='accuracy', min_features_to_select=1, n_jobs=2)
selector.fit(X.data, X.target)
print(selector.get_feature_names_out())

['petal length (cm)' 'petal width (cm)']


## Exhaustive (All combinations)

In [77]:
from itertools import combinations, chain # ต่อกันคือใช้ chain
# ต่อจากอะไร เช่น iris มี 4 อย่าง (feature) เราก็ต้องเรียก 1 เสร็จ ก็เลือก2 , 3, 4 เท่าด้านล่างครั้ง แล้วเอาแต่ละอันมาบวกกัน

In [78]:
for i in range(1, 5):
    for x in combinations([0, 1, 2, 3], i): # เริ่มที่ 0
        print(x)

(0,)
(1,)
(2,)
(3,)
(0, 1)
(0, 2)
(0, 3)
(1, 2)
(1, 3)
(2, 3)
(0, 1, 2)
(0, 1, 3)
(0, 2, 3)
(1, 2, 3)
(0, 1, 2, 3)


In [79]:
n_features = X.data.shape[1]
chain.from_iterable(combinations(range(n_features), i) for i in range(1, 5)) 

In [80]:
from sklearn.model_selection import StratifiedKFold

In [81]:
from sklearn.model_selection import cross_val_score

In [82]:
def EFS(estimator, X, Y, cv=5, verbose=False): #Exhaustive feature selection
    n_features = X.shape[1]
    subsets = chain.from_iterable(combinations(range(n_features), i) for i in range(1, 5))
    best_score = -np.inf
    best_subset = None#คงไม่น้อยกว่า อนัน อยู่แล้ว
    for i, subset in enumerate(subsets):
        subset = list(subset)
        score = cross_val_score(estimator, X.iloc[:, subset], Y, cv=cv).mean() # ถ้า score ใหม่ดีกว่า 
        # เก็บเป็นค่าใหม่ที่ดีสุด 
        if score > best_score:
            best_score = score
            best_subset = subset
        if verbose:
            print(i, score, subset)
    return X.columns[best_subset]

In [83]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3)
selected = EFS(clf, X.data, X.target, cv=StratifiedKFold(5), verbose=True)
print(selected)

0 0.6199999999999999 [0]
1 0.5066666666666666 [1]
2 0.9400000000000001 [2]
3 0.96 [3]
4 0.74 [0, 1]
5 0.9466666666666667 [0, 2]
6 0.9533333333333334 [0, 3]
7 0.9333333333333333 [1, 2]
8 0.9400000000000001 [1, 3]
9 0.9533333333333334 [2, 3]
10 0.9400000000000001 [0, 1, 2]
11 0.9466666666666667 [0, 1, 3]
12 0.9733333333333334 [0, 2, 3]
13 0.96 [1, 2, 3]
14 0.9666666666666668 [0, 1, 2, 3]
Index(['sepal length (cm)', 'petal length (cm)', 'petal width (cm)'], dtype='object')


In [ ]:
# เปลี่ยนจาก list ของ case ([0, 1, 2, 3]) เป็น tuple → ทำให้เป็น index และ ค่า value เพื่อ plot